name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: false
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6.2.1
      - name: Run tests
        run: make test
      - uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
#      - uses: go-semantic-release/action@v1
#        id: semver
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          allow-initial-development-versions: true
#          force-bump-patch-version: true
